### ISSUE TITLE
Link text truncated on Org branding banner

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#103]
Another vertical bar went missing, this time in the Org branding banner (see screenshot), but then it came back. Leaving this comment here to double check but it appears to have fixed itself.

I also noticed that long link labels appear with an ellipse (see screenshot). This is okay but this label should be displayed in full as it's not longer than the width of the banner space. Try increasing max length of link text display.

![screen shot 2018-02-24 at 3 38 58 pm](https://user-images.githubusercontent.com/12703638/36636298-eb1a7748-1978-11e8-8304-14ef81a1d6a0.png)

**Comment by briri** [comment]
ok will increase the width a bit. I've noticed the lines appear/disappear occasionally as well. Its typically due to the width of the browser window. If it becomes an issue we can look at alternative methods for creating and displaying those bars

**Comment by stephaniesimms** [comment]
thanks for increasing a bit. that should help. and i noticed the bars coming and going. we can sort it out later, yes. closing this for now.

**Comment by stephaniesimms** [comment]
longer space is good. closing.
