### ISSUE TITLE
Update po file for US English

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#107]
I found a few places where I edited the current .po file over the past couple of days and the changes aren't reflected in the app. In addition, I'm collecting a list of banner alert messages and other new features (Usage page) with text that's missing from the current .po file. 

@briri please advise on the best approach to updating and correcting the US English translation.

**Comment by briri** [comment]
there are a few gems that are not a part of the app.po. I had gone through and updated 'organisation' to 'organization' but may have missed some things. They can be found in:
- `config/locales/bootstrap/en_US.bootstrap.yml`
- `config/locales/contact_us/contact_us.en_US.yml`
- `config/locales/devise/devise.en_US.yml`

We also use the 'date' and 'time' sections of the `config/locales/en_US.yml` file. The rest of the remaining content in that file is no longer used, so not to worry no need to update it! We will/should clean it out after MVP

**Comment by stephaniesimms** [comment]
i think we fixed all the things now. closing this issue.
