### ISSUE TITLE
Edit profile page changes for Shibboleth

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmp#12]
- Remove the shibboleth link/unlink functionality from the edit profile page.
- If the user has logged in via shibboleth (they have a record in `user_identifiers` for shib) then hide the passwords tab.

**Comment by stephaniesimms** [comment]
I can't test this until Shib is hooked up @briri . But some notes based on the current profile page:
- disable changes for user email by graying it out as in DMPTool (screenshots 1-2)
- hide the icon and message "Your account has been linked to your institution..." for all users. This will just be confusing to them. we can potentially reintroduce it if we add an account recovery workflow.
- hide the password tab for Shib users 

1 - DMPTool w/email address grayed out for Shib users so they can't make changes
<img width="854" alt="screen shot 2018-01-26 at 1 11 50 pm" src="https://user-images.githubusercontent.com/12703638/35461214-cc1d12fe-029b-11e8-8031-01671b2c1889.png">

2 - Roadmap profile page
<img width="722" alt="screen shot 2018-01-26 at 1 17 51 pm" src="https://user-images.githubusercontent.com/12703638/35461217-d1125864-029b-11e8-9729-9e1e20f59235.png">

**Comment by briri** [comment]
closing this old one as I think its no longer applicable
