### ISSUE TITLE
UCSC Org template count incorrect in Orgs table

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#142]
This only appears to be affecting DMPTool production data (not an issue on roadmap stage - see screenshots below). I noticed that the main Orgs table indicates UCSC has 2 templates. But their Templates page clearly shows that they have none. The total reflected on roadmap stage is correct, however. I don't think they ever had any templates (nothing removed so not a versioning-related issue). 

I only noticed this for UCSC - will note if this is happening for other orgs.

DMPTool production
![screen shot 2018-04-04 at 9 16 55 am](https://user-images.githubusercontent.com/12703638/38320496-9bce48e2-37e9-11e8-97ed-9d358059f630.png)

![screen shot 2018-04-04 at 9 17 18 am](https://user-images.githubusercontent.com/12703638/38320536-b517f7ee-37e9-11e8-9a63-afde322e4f2b.png)

Roadmap stage
![screen shot 2018-04-04 at 9 18 32 am](https://user-images.githubusercontent.com/12703638/38320545-bcb0e920-37e9-11e8-9ca7-c3441c7d651b.png)

![screen shot 2018-04-04 at 9 18 10 am](https://user-images.githubusercontent.com/12703638/38320556-c4cd7e02-37e9-11e8-8c7d-7f7e80851120.png)

**Comment by briri** [comment]
This should be ok on dmptool-stg. Can you verify @stephaniesimms. If so the fix will be moved into production along with the v2 upgrade
