### ISSUE TITLE
Header navigation changes

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmp#17]
Update the baseline header navigation

**Comment by rhu001** [comment]
Header (public not logged in version): https://h90c3m.axshare.com/#g=1&p=header__public_
Header (logged in non-admin version): https://h90c3m.axshare.com/#g=1&p=header__logged_in_non-admin_
Header (logged in admin version): https://h90c3m.axshare.com/#g=1&p=header__logged_in_admin_

Note: Pull down menus for Select Language, Explore, and Admin Features should have a drop shadow applied.

**Comment by briri** [comment]
Updated the logged out version of the header 

![screen shot 2018-01-17 at 2 22 53 pm](https://user-images.githubusercontent.com/1204467/35070381-f3d31480-fb91-11e7-838f-510b4d46d286.png)
![screen shot 2018-01-17 at 2 08 34 pm](https://user-images.githubusercontent.com/1204467/35070400-032929ec-fb92-11e7-9fde-5dbbbd930aa1.png)
![screen shot 2018-01-17 at 2 16 16 pm](https://user-images.githubusercontent.com/1204467/35070401-0342930a-fb92-11e7-81ae-7e367206ab15.png)
![screen shot 2018-01-17 at 2 16 28 pm](https://user-images.githubusercontent.com/1204467/35070402-0356099e-fb92-11e7-84bb-4eef808bd636.png)

**Comment by briri** [comment]
@rhu001 and @stephaniesimms do we have a page in the wireframes for the logged in version of the header section?

Here is what it looks like with the existing org branded sub menu:
![screen shot 2018-01-17 at 2 49 06 pm](https://user-images.githubusercontent.com/1204467/35071510-c2ceaada-fb95-11e7-8ab4-4412cb7c7ae4.png)

**Comment by stephaniesimms** [comment]
the logged in version replaces the dmptool logo w/the org logo - see screenshot 
and for admins there's an extra item in the main nav

<img width="1040" alt="screen shot 2018-01-17 at 3 45 11 pm" src="https://user-images.githubusercontent.com/12703638/35073390-7553c328-fb9d-11e7-84c9-84271f99bc06.png">

**Comment by briri** [comment]
thanks for the link to the wireframe @stephaniesimms 

Here are some screenshots of the menu when logged in:
![screen shot 2018-01-18 at 11 18 04 am](https://user-images.githubusercontent.com/1204467/35116980-f79e2acc-fc41-11e7-8674-2e380e0f5397.png)

![screen shot 2018-01-18 at 11 18 17 am](https://user-images.githubusercontent.com/1204467/35116991-0043dae6-fc42-11e7-8651-2a6b8b12bd57.png)

![screen shot 2018-01-18 at 11 22 10 am](https://user-images.githubusercontent.com/1204467/35117003-08bc061c-fc42-11e7-9ea0-eb6f2db852c1.png)
(note that 'Institutions' is only plural for a super admin)

**Comment by briri** [comment]
Version if Institution has no logo and no links defined (contact email is a required field so would always appear)
![screen shot 2018-01-18 at 11 29 16 am](https://user-images.githubusercontent.com/1204467/35117223-de424e5e-fc42-11e7-8952-5eb1e5c57e75.png)

Version with logo but no links
![screen shot 2018-01-18 at 11 31 55 am](https://user-images.githubusercontent.com/1204467/35117353-458f089a-fc43-11e7-90fe-89fca0410335.png)

Version with links but no logo 
![screen shot 2018-01-18 at 11 26 13 am](https://user-images.githubusercontent.com/1204467/35117293-178da118-fc43-11e7-95a3-7314bec8aaf2.png)

**Comment by stephaniesimms** [comment]
i wondered about cases where there are links but no logo - @rhu001 it looks odd to have so much white space between them. for current dmptool we have a different order (screenshot below for comparison). DMP Assistant just replaces their logo w/an Org logo (https://github.com/DMPRoadmap/roadmap/issues/156), but we definitely need the Org name somewhere. The alternative is requiring a logo or we upload one for new Orgs ourselves, although that isn't ideal.

![screen shot 2018-01-19 at 3 25 54 pm](https://user-images.githubusercontent.com/12703638/35176310-1a0cdb62-fd2d-11e7-8240-33267fa5eb77.png)

**Comment by rhu001** [comment]
@briri The svg logo for the header is available in this folder. (https://drive.google.com/drive/folders/1rjEpQ6jT3VUSgf6PbfCsj2fTcsIa3d9A?usp=sharing) The file is named "DMPTool_logo_blue_shades_v1b3b.svg."

**Comment by rhu001** [comment]
@briri Updated header with new "contained" Org name, logo, and links.
![fireshot screen capture 004 - header logged in non-admin - h90c3m_axshare_com_ g 1 p header__logged_in_non-admin](https://user-images.githubusercontent.com/23642279/35364836-3272cad4-0126-11e8-9410-8bffff34f6f9.png)

**Comment by stephaniesimms** [comment]
change Account to "My Account"

**Comment by briri** [comment]
All of the changes mentioned above are complete and I'm no longer receiving the above error. closing this old header ticket out. Please create new tickets for changes to the headers as needed
