### ISSUE TITLE
Footer navigation and styling

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmp#18]
Update the footer

**Comment by rhu001** [comment]
Sample page with newly styled footer. (https://h90c3m.axshare.com/#g=1&p=header__logged_in_non-admin___dashboard_)

**Comment by briri** [comment]
implemented with grey social media icons (using font-awesome icons)

![screen shot 2018-01-16 at 3 57 38 pm](https://user-images.githubusercontent.com/1204467/35018394-19c73b38-fad6-11e7-924a-4fe7b3f56213.png)

**Comment by mxsstrong** [comment]
love the blue!

________________________________

**Comment by rhu001** [comment]
@briri The svg logo for the footer is available in this folder. (https://drive.google.com/drive/folders/1rjEpQ6jT3VUSgf6PbfCsj2fTcsIa3d9A?usp=sharing) The file is named "DMPTool_logo_blue_shades_v1b3b_no_tag.svg."

**Comment by stephaniesimms** [comment]
i'd like to see the footer without the blue bar - maybe a way to cut down on clutter at the bottom of the page? we can discuss Mon in context of homepage design.

**Comment by stephaniesimms** [comment]
make hyperlinks in footer for the following; same as current DMPTool: 
UC3 - http://www.cdlib.org/services/uc3/
CDL - https://www.cdlib.org/

**Comment by briri** [comment]
Going to close this initial footer ticket. Please create others as necessary for changes to the footer
