### ISSUE TITLE
CSS styling changes

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmp#4]
Generic issue for capturing CSS styling changes required for DMPTool (logo, colors, fonts, table layout, etc)

Logo: http://www.cdlib.org/services/uc3/about/logos.html

- Note: reduce font sizes and economize page layout for Project Details especially so users don't have to scroll down to find the Submit button
- remove heavy grid lines for tables
- remove solid color bar for accordions (switch back to white/plain) and move +/- to left side; do this for all accordions on write plan and template pages (screenshots 1, 2)
- make message bar at top of page shorter/slimmer (screenshot 3)
- tab styling (screenshot 4)

1 - Roadmap accordions
![screen shot 2018-01-24 at 1 34 58 pm](https://user-images.githubusercontent.com/12703638/35358561-e7a71f6a-010b-11e8-8f86-01454f7d9470.png)

2 - wireframes showing desired styling
![screen shot 2018-01-24 at 1 36 30 pm](https://user-images.githubusercontent.com/12703638/35358568-ea96047a-010b-11e8-9a47-950056cc6504.png)

3 - Message bar too thick
![screen shot 2018-01-25 at 3 45 52 pm](https://user-images.githubusercontent.com/12703638/35418441-169272d0-01e7-11e8-964a-82a791844d68.png)

4 - Tab styling needs attention; including on the Sign In/Create account modal
![screen shot 2018-01-11 at 11 08 25 am](https://user-images.githubusercontent.com/1204467/34852255-94f887fa-f6e2-11e7-83c7-f3f77640907c.png)

**Comment by rhu001** [comment]
Font style: Arial
Color Hex: Dark Green for Header Font, H1 background banner, and H2/H3 font color (3a7008)

**Comment by rhu001** [comment]
@briri 
Font style: Arial
Color Hex: Dark Green for Header Font, H1 background banner, and H2/H3 font color (3a7008)

**Comment by briri** [comment]
Going to close this initial css ticket. Please create others as necessary for changes to the styling
