### ISSUE TITLE
Add in LDAP logic to handle password resets for migrated users

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmp#45]
Add in the LDAP password reset interrupt we tested on the roadmap codebase.

**Comment by mxsstrong** [comment]
Here is a script to convert the LDAP export file (LDIF) to CSV for input into the database.  

https://gist.github.com/dansimau/674203

cat export_ldap_prd.ldif | ./ldif-to-csv.sh objectClass mail uid displayName userPassword > all_reqd_fields.csv

**Comment by stephaniesimms** [comment]
@bhavi - I tried entering various usernames for existing DMPTool accounts (in production) and it didn't find any of them (see message in screenshot below)

![screen shot 2018-02-14 at 7 36 24 pm](https://user-images.githubusercontent.com/12703638/36239586-b0d2ce7a-11bf-11e8-9aaa-b73c74b694c2.png)

**Comment by stephaniesimms** [comment]
will retest after migration test-run today

**Comment by stephaniesimms** [comment]
success! I was able to log in to a couple of LDAP accounts. there are just a couple of small things that should be changed to improve flow and messaging:
- after I successfully log in the current behavior leaves me on the Forgot email? page (screenshot 1). the desired behavior is to take users to My Dashboard.
- after I enter my username the modal pops up with my pre-populated email as expected. however, there is an error message on the main page behind it (screenshot 2) that I can't read. desired behavior is to not trigger a message at all so users aren't wondering what it says.

1 - Successful login should take user to My Dashboard
![screen shot 2018-02-20 at 3 00 53 pm](https://user-images.githubusercontent.com/12703638/36454213-d80066a8-164f-11e8-861e-d6206a8e129d.png)
 
2 - remove Error message on main page (behind modal)
![ldap-test](https://user-images.githubusercontent.com/12703638/36454242-eaee6d3c-164f-11e8-95d5-a8959956a8a2.png)

**Comment by briri** [comment]
@bhavi if you are working on this, please do so in the development branch not the dmptool-login branch.

**Comment by stephaniesimms** [comment]
working as expected now. closing.
