### ISSUE TITLE
Display Example and Default Answers below text editor

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#47]
If Example and/or Sample answers are provided, display them below the question and text editor (not above as in screenshot below). Order should be Question, text editor, example answer, Save button.

![screen shot 2018-01-22 at 3 24 53 pm](https://user-images.githubusercontent.com/12703638/35249848-82e6c780-ff88-11e7-95fe-87ca6dc0b748.png)

**Comment by briri** [comment]
This is already moved (in the core Roadmap code if I'm not mistaken)
![screen shot 2018-02-14 at 9 58 05 am](https://user-images.githubusercontent.com/1204467/36219877-a9ee5dd8-116d-11e8-8911-d80c3d77adde.png)

**Comment by briri** [comment]
used BCO DMO template to test

**Comment by stephaniesimms** [comment]
working as expected. closing issue.
