### ISSUE TITLE
Open Guidance links in a new tab

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#48]
When I click a guidance link on DMP2 stage it opens the page in the same tab. This happens in the template editing area and plan writing pages. Desired behavior is to open the link in a new tab. This works as desired on Roadmap stage server but for mysterious reasons it's not the same on DMP stage.

**Comment by briri** [comment]
that's because the data on roadmap-stg was migrated and contains `target="_blank"` in the link. I will auto-add that to these links via JS

**Comment by stephaniesimms** [comment]
all of the links I clicked on from public Funder Requirements page and within plan guidance still open in the same tab. I'm testing on dmptool-stage and dmp2-stg because I don't have my work laptop at home. will test again on dmptool-dev tomorrow but this doesn't appear to be working as expected.

**Comment by stephaniesimms** [comment]
and this is working as expected now. closing.
