### ISSUE TITLE
Revise Org selection on profile page

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmp#5]
Update the org selection area of the edit profile page.
- remove the "My org isn't listed" link and other org textbox and remove related JS functionality
- update the controller so that if the user leaves the org box blank they are auto-assigned to the org with `is_other=true`

TODO: determine how to deal with account recovery and when a user changes their org affiliation.

**Comment by stephaniesimms** [comment]
As an Org Admin I just removed my Org affiliation on the edit profile page and got a friendly note that my changes were saved. The org branding banner switched to Non Partner Institution (screenshots below). We should add an "Are you sure" step for users with admin privileges to reinforce the message in the tooltip that they will lose their admin privileges if they take this action. I will also create a new issue in Roadmap repo to list privileges here on the profile page.

Desired changes:
- revise the tooltip message to be extra clear: "Select an organization from the list or leave this field blank if your organization is not listed. Warning: If you have administrative privileges, changing your organization will remove them."
- add a modal step for admin users: "Are you sure you want to change your Organization? This action will result in the loss of your administrative privileges" 
- do not display "Non partner org" in the banner - this should display the DMPTool logo for all users with no Org

<img width="759" alt="screen shot 2018-01-26 at 1 37 59 pm" src="https://user-images.githubusercontent.com/12703638/35461933-b711492c-029e-11e8-8429-278f03ce5074.png">

<img width="650" alt="screen shot 2018-01-26 at 1 36 57 pm" src="https://user-images.githubusercontent.com/12703638/35461953-d231aa8a-029e-11e8-969a-6e6a8b15e09f.png">

**Comment by briri** [comment]
closing this old one as I think its no longer applicable
