### ISSUE TITLE
Add ability to author static content with Markdown

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmp#50]
Allow contributors to manage static content through Markdown syntax.

**Comment by briri** [comment]
Added a Markdown template handler and setup stub markdown template files for all of the new pages that can be accessed via the navigation and footer menus.

Pages are currently located in (development branch) the static_pages views folder with a file extension of 'html.md': https://github.com/CDLUC3/dmp/tree/development/app/views/static_pages

You can use standard Markdown to create the files and then wrap any translatable text with the following markup: `<%= _('Some translatable text here') %>`. This will instruct the template handler to swap in localized content if available (e.g. Brazilian Portuguese, French, etc.)

**Comment by stephaniesimms** [comment]
hooray! i will start on content muy pronto. thanks @briri
