### ISSUE TITLE
Update logo & favicon for DMPTool blog

### ISSUE THREAD

**Issue by mxsstrong** [CDLUC3/dmp#55]
DMPTool Blog should have logos/favicon updated to match the blue logos from green.

https://blog.dmptool.org/ - for example of square green DMPTool logo 
https://dmptool.org/ - for example of favicon using just stack (excludes word "DMPTool")

To update favicon:
Go to Administration Screen > Appearance > Customize.
Click Site Identify.
Click Select Image at Site Icon section, upload the image file you prepared in the above step from Upload Files tab screen, and click Select.

**Comment by rhu001** [comment]
Here are the updated logo and favicon for the DMPTool blog.

Logo: https://drive.google.com/file/d/1fyujpHmqJPm6RD507zNCiQgP8BnKG4qP/view?usp=sharing
Favicon: https://drive.google.com/file/d/1SSAvDRIb5PG1OoxFjm7grN9QyuAFLuPQ/view?usp=sharing

**Comment by stephaniesimms** [comment]
the moldy sandwich is now blue instead of green. closing issue.

**Comment by briri** [comment]
the favicon is too small. I think this is due to all the white space (well transparent background space) around it. @rhu001 you can view it on the dmptool-stg.cdlib.org server

**Comment by stephaniesimms** [comment]
these files are for the DMPTool blog only. I already updated everything there using the png file. there's a separate issue for the app favicon #56
