### ISSUE TITLE
Update favicon for DMPTool 

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#56]
Please complete the following fields as applicable:

**Expected behaviour:**
DMPTool servers should have logos/favicon updated to match the new blue logo.

**Actual behaviour:**
Logos/favicons are still green or DMPonline orange.

**Comment by rhu001** [comment]
Here is the updated blue favicon for the DMPTool site. (https://drive.google.com/file/d/1MtQTEjW-cMkmOBxG4KUG-zDqAme_B13W/view?usp=sharing)

**Comment by stephaniesimms** [comment]
the favicon is too small. I think this is due to all the white space (well transparent background space) around it. @rhu001 you can view it on the dmptool-stg.cdlib.org server

**Comment by stephaniesimms** [comment]
this one will work for now. we can always swap for the sandwich-only look later after it gets resized.
