### ISSUE TITLE
Update English US translation file

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmp#58]
I just ran the Gettext script which pulled all of the latest translatable text from the site. 

Please update the following file: `config/locale/en_US/app.po`

It looks like the headings (e.g. ### <%= _('What is the DMPTool') %>) in the Markdown files was skipped by the script referenced above. We may need to find a different solution for them.

**Comment by briri** [comment]
I stubbed out some instructions for external parties who want to add translations: https://github.com/CDLUC3/dmp/wiki

**Comment by briri** [comment]
@stephaniesimms when you get around to this, update the 2nd part of each translation not the first. The first represents what it looks like in the codebase, the second is for the localized translation. For example:
```yaml
msgid "Add Annotations"              <--- Codebase
msgstr "Add Customizations"       <--- Translation
```

**Comment by stephaniesimms** [comment]
this file is ready now: https://github.com/CDLUC3/dmp/blob/development/config/locale/en_US/app.po

**Comment by stephaniesimms** [comment]
new translation file just deployed and looking good so far. closing issue.
