### ISSUE TITLE
Remove other org from Org selection boxes

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmp#6]
Update the shared code for Org selection (the auto-complete box) so that it does not include the org with `is_other=true`.

**Comment by briri** [comment]
Removed other org textbox and link and added '?' style popover/tooltip. That lets them know to select an item from the list or leave blank:
![screen shot 2018-01-08 at 1 08 13 pm](https://user-images.githubusercontent.com/1204467/34695186-bb88724c-f47e-11e7-990e-da79a74a22b6.png)

For Org Admins it also displays a warning about losing credentials:
![screen shot 2018-01-08 at 1 16 42 pm](https://user-images.githubusercontent.com/1204467/34695214-d68b56b8-f47e-11e7-9c1e-889428612a73.png)

**Comment by stephaniesimms** [comment]
@briri - I requested a revision for the tooltip on the profile page in related issue #5 along w/some other changes. the regular version for non-admin users looks good.
