### ISSUE TITLE
Sign In modal redesign

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#62]
Stub issue for a new wireframe @rhu001

**Comment by rhu001** [comment]
Updated sign in wireframe.

![image](https://user-images.githubusercontent.com/23642279/36514377-004ae898-1729-11e8-8d13-83f03805d044.png)

**Comment by rhu001** [comment]
@briri We may need to make the font for the "Step" lines a bit smaller. And if we're not using longer labels for the buttons then we can make the buttons smaller.

**Comment by stephaniesimms** [comment]
we were doing some futzing earlier today @rhu001 - should have something to review on stage soon

**Comment by stephaniesimms** [comment]
ready for feedback. closing issue.

**Comment by stephaniesimms** [comment]
ready for feedback now. closing.
