### ISSUE TITLE
Revise My Dashboard column headings

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#66]
Change the following column headings based on usability testing feedback:

- change "Role" to "Permissions"
- Edited to "Last edited" (make this change here and throughout the site for tables with edited/updated column headings, e.g., Org table below the main user plans table should also say "Last edited" instead of "Updated" - also Funder Requirements table...)

![screen shot 2018-02-14 at 3 40 33 pm](https://user-images.githubusercontent.com/12703638/36233983-7298061a-119d-11e8-94da-bf7c3686251b.png)

**Comment by stephaniesimms** [comment]
I don't see the changes on dmptool-stg @briri

**Comment by briri** [comment]
Make sure your account's language setting is US English. I made those changes in the app.po file

**Comment by stephaniesimms** [comment]
yes, it's set to US English (see screenshot) and the changes don't appear in the table

![screen shot 2018-02-19 at 1 39 02 pm](https://user-images.githubusercontent.com/12703638/36398108-571b3aa2-157a-11e8-97ea-8a4c6a488e09.png)

**Comment by stephaniesimms** [comment]
@briri I just checked again and now it's showing "Permissions" but not "Last edited" (screenshot). also the date column is wrapping - hopefully you can make that not happen

![screen shot 2018-02-20 at 4 12 17 pm](https://user-images.githubusercontent.com/12703638/36456290-093d5a88-1659-11e8-95b9-0c0b240fe36a.png)

**Comment by briri** [comment]
the updated translation file should fix this once the '# fuzzy' comments have been removed. We have also updated the migration script to default the language to 'en-US'

**Comment by briri** [comment]
seems to be fixed now that the app.po has been updated. thanks for taking care of that @stephaniesimms!

**Comment by stephaniesimms** [comment]
yes fixed! i just made a note in the pre-launch checklist to verify that US-English is the default in both the session selector (top right) and for all user accounts in dmptool. i've noticed that mine keep switching back to GB-English.
