### ISSUE TITLE
Adjust layout and language for Forgot password?

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#69]
- make the Username field shorter (using the standard short/half width same as #68 )
- revise heading: "Forgot password?"
- revise message below heading: "Please enter your email below and we will send instructions to reset your password."
- revise blue notice message after user enters email (screenshot 2): "Notice: You will receive an email with instructions to reset your password in a few minutes." 
- revise failure message if email address not found (screenshot 3): "There is no account associated with that email address. Please try again or Contact us."
- format this message with a yellow bar and "x" icon like other error messages

1 - 
![screen shot 2018-02-14 at 7 47 58 pm](https://user-images.githubusercontent.com/12703638/36239666-4dca451e-11c0-11e8-9286-85840765b92d.png)

2 -
![screen shot 2018-02-14 at 7 53 17 pm](https://user-images.githubusercontent.com/12703638/36239728-cf11a766-11c0-11e8-81ed-dbf0b784dce9.png)

3 - 
![screen shot 2018-02-14 at 7 55 46 pm](https://user-images.githubusercontent.com/12703638/36239815-7e3a24c0-11c1-11e8-97e8-eaa3ed1f2d74.png)

**Comment by stephaniesimms** [comment]
a couple of small revisions to the messages:
- remove "about how" from the success message so the text is as follows: "Notice: You will receive an email with instructions to reset your password in a few minutes."
- add an "x" symbol and "Error" to message for incorrect email so the text is as follows: "x Error: There is no account associated with that email address. Please try again or Contact us."

**Comment by stephaniesimms** [comment]
error message is fixed. please just revise the text for the success/Notice message (screenshot below) as follows:
- remove "about how" from the success message so the text is as follows: "Notice: You will receive an email with instructions to reset your password in a few minutes."

![screen shot 2018-02-19 at 1 35 12 pm](https://user-images.githubusercontent.com/12703638/36398033-fde3b130-1579-11e8-8234-22f7ad54a52c.png)

**Comment by briri** [comment]
This message is stored in devise's localized files. I had updated the en_US version but not the en_GB. Will update that one as well

**Comment by stephaniesimms** [comment]
ah, thanks @briri
