### ISSUE TITLE
Adjust layout and language for Change password modal

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#70]
- make "New password" field shorter (same as #68 #69)
- delete second field to "Confirm password" (the show pw tickbox makes this redundant)
- revise message for tickbox to make it singular "Show password"

![screen shot 2018-02-14 at 8 01 44 pm](https://user-images.githubusercontent.com/12703638/36239923-76abe65c-11c2-11e8-8667-374e45aa23da.png)

**Comment by briri** [comment]
Its easier for me to remove the 'Show passwords' checkbox. Devise wants a password and confirmation.

**Comment by stephaniesimms** [comment]
ok that's fine here. was just aiming for consistency with main create account page, but this can have the pw confirmation if that's easier.

**Comment by stephaniesimms** [comment]
layout looks good. closing issue.
