### ISSUE TITLE
Do not allow users w/Shib accounts to change email

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#71]
Currently I can log in w/UCOP shib and change my email address on my profile page. For all users with accounts based on institutional credentials the email field should be grayed out as in DMPTool. We cannot allow them to change this until we establish an account recovery workflow.

Also revise the message at the top of the page:
"Please note that your email address is also your username. If you change this remember to use your new email address on sign in. If your account is created with your institutional credentials you must contact us to change your email."

![screen shot 2018-02-14 at 8 12 13 pm](https://user-images.githubusercontent.com/12703638/36240081-b0c0d8e2-11c3-11e8-8335-d95ec59ad384.png)

**Comment by briri** [comment]
I did the same for the organisation (alleviates the existing issue with org admins losing credentials accidentally). We shouldn't allow it until we figure out the account recover stuff.
Super admins can still change their org on the templates page

**Comment by stephaniesimms** [comment]
looks good now. closing.
