### ISSUE TITLE
Change owner of BCO-DMO template to NSF

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#73]
I can't update the template owner via the UI. But using the new create plan logic we need to associate the "BCO-DMO NSF OCE..."  template with NSF (the actual funder, not the org who created the template). Please make this change in the dmp2-stage database. I will make any updates to the template on their behalf going forward.

**Comment by briri** [comment]
done on dmptool-stg and dmp2-stg

**Comment by stephaniesimms** [comment]
excellent thanks! closing.
