### ISSUE TITLE
Replace clipboard/tadpole image

### ISSUE THREAD

**Issue by rhu001** [CDLUC3/dmp#75]
When the clipboard/tadpole homepage image is being displayed at its max resolution, the tadpole part of the image is being cut off. We have recut the image so that more of the tadpoles are showing at the max resolution.

https://drive.google.com/drive/folders/1AtnltPMi3Ndj4lIhJKrc2twNi9e7xDzD

**Comment by stephaniesimms** [comment]
it is crucial that we have enough tadpole. thanks @rhu001 - checking it out now and looks good
