### ISSUE TITLE
Profile page won't save when user is shibbolized

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmp#76]
Save warns that the email address is blank.

**Comment by stephaniesimms** [comment]
i navigated to my profile page and clicked Save. now my Org affiliation is blank and grayed out. when I tried signing out and back in my Org remains blank. this is a related or new bug.

![screen shot 2018-02-19 at 11 27 28 am](https://user-images.githubusercontent.com/12703638/36394175-e5ebbcf6-1567-11e8-855e-95c6e1d64a72.png)
