### ISSUE TITLE
Update static pages and add external links to main menu

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#83]
Update About, FAQ, Data Management General Guidance pages w/ revised markdown files. 

Add links to external resources (dmp Github wiki) and an arrow icon to the Learn main menu next to these items
- For Administrators https://github.com/CDLUC3/dmp/wiki/Help-for-Administrators
- For Developers https://github.com/CDLUC3/dmp/wiki/Help-for-Developers

![screen shot 2018-02-19 at 8 07 47 pm](https://user-images.githubusercontent.com/12703638/36407094-a2e9eda8-15b0-11e8-9b5f-89682e4d32a6.png)

**Comment by briri** [comment]
using the font-awesome version of an external link icon
![screen shot 2018-02-22 at 1 43 44 pm](https://user-images.githubusercontent.com/1204467/36565815-7a001ba6-17d6-11e8-88ad-ae45f7d9093b.png)

**Comment by stephaniesimms** [comment]
font awesome icon looks awesome! and thanks for adding to the footer links also.
