### ISSUE TITLE
Add markdown files for static pages

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#86]
https://github.com/CDLUC3/dmp/tree/development/app/views/static_pages

Create new markdown files for: 
Quick Start Guide https://dmptool.org/help
Promote the DMPTool https://dmptool.org/promote (replaces For Developers page in menu)

**Comment by stephaniesimms** [comment]
all good now. thanks.

**Comment by briri** [comment]
promote file is in place

**Comment by stephaniesimms** [comment]
yes it is.
