### ISSUE TITLE
Login dialog window blocks email informative message

### ISSUE THREAD

**Issue by mxsstrong** [CDLUC3/dmp#87]
Please complete the following fields as applicable:

**Expected behaviour:**
For LDAP users, after a user retrieves their email address the login dialog window appears with the email address populated.  

**Actual behaviour:**
The correct behavior is occuring, however the display of the diaglog window is blocking the message.  The  alert message is red which could indicate to a user that there is an error, but they can't read the message because it's blocked.  So it's not a great experience. 

![screen shot 2018-02-21 at 9 21 47 am](https://user-images.githubusercontent.com/810543/36495430-02d8e496-16ea-11e8-946f-774628f6176c.png)

**Steps to reproduce:**
Click on the Forgot email? link in the login dialog box, enter username.

 Perhaps removing the red alert message and just entering the email in the dialog box is enough.

**Comment by stephaniesimms** [comment]
duplicate issue
