### ISSUE TITLE
Footer: Accessibility links should point to CDL Accessibility page

### ISSUE THREAD

**Issue by mxsstrong** [CDLUC3/dmp#88]
Please complete the following fields as applicable:

**Expected behaviour:**
At the footer, the Accessibility link should go to the CDL Accessibility page - https://www.cdlib.org/about/accessibility.html

**Actual behaviour:**
The Accessibility link goes to the UCOP Accessibility page. 

**Steps to reproduce:**
go to dmptool-stg.cdlib.org, scroll down to footer to see Accessibility link

**Comment by stephaniesimms** [comment]
link updated.
