### ISSUE TITLE
Reintroduce the shibboleth discovery service page

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmp#9]
Update the branding.yml file in (dmptool_config repo) so that the shibboleth discovery service page is available again `views/orgs/shibboleth_ds.html.erb`. This page is accessed when the user clicks on the 'Institutional credentials' button on either the sign in or create account panels.

- Make sure any JS is converted over to ES6. 
- Make sure all orgs appear in the list (except `is_other=true`)
- Add logic that brings the user to our custom login page if their Org identifier record does not have the Shib entity info (See ticket #103)

**Comment by briri** [comment]
Reintroduced the Org selection page and updated to match wireframe. Not that 'institutional credentials' has been changed to 'Your institution'
![screen shot 2018-01-11 at 11 08 09 am](https://user-images.githubusercontent.com/1204467/34852396-417f4a40-f6e3-11e7-9487-771d465c0877.png)

After the user clicks the 'Institutional credentials' button the following modal is displayed
![screen shot 2018-01-11 at 11 08 46 am](https://user-images.githubusercontent.com/1204467/34852424-6cc30138-f6e3-11e7-93d3-5151d8339b41.png)

The user can either select an Org from the auto complete box or click the 'See the full list ...' link which will expand the list of orgs:
![screen shot 2018-01-11 at 11 09 00 am](https://user-images.githubusercontent.com/1204467/34852425-6cdc1312-f6e3-11e7-9fb4-03cc98e633cc.png)

**Comment by stephaniesimms** [comment]
this page looks great and is working as expected. i just can't test the final step until we have Shib hooked up. closing issue.
