### ISSUE TITLE
Exception error when trying to export/download a plan

### ISSUE THREAD

**Issue by mxsstrong** [CDLUC3/dmp#95]
https://dmptool-dev.cdlib.org/plans/1265/download - this isn't occurring in stage 

![screen shot 2018-02-23 at 8 23 00 am](https://user-images.githubusercontent.com/810543/36604537-cf56bd5c-1872-11e8-9ee4-b8a9633733b1.png)
When I try to export a plan I receive an error

ActiveRecord::RecordNotUnique in PlansController#export
Mysql2::Error: Duplicate entry 'ExportedPlan-265-export' for key 'index_settings_on_target_type_and_target_id_and_var': INSERT INTO `settings` (`value`, `var`, `target_type`, `target_id`, `created_at`, `updated_at`) VALUES ('---\nformatting:\n :margin:\n :top: 25\n :bottom: 20\n :left: 12\n :right: 12\n :font_face: Arial, Helvetica, Sans-Serif\n :font_size: 10\nmax_pages: 3\nfields:\n :admin:\n - project_name\n - project_identifier\n - grant_title\n - principal_investigator\n - project_data_contact\n - project_description\n - funder\n - institution\n - orcid\n :questions: :all\ntitle: \'\'\n', 'export', 'ExportedPlan', 265, '2018-02-23 16:19:54', '2018-02-23 16:19:54')

**Comment by stephaniesimms** [comment]
@bhavi - I can download most of my plans on dev and stage. So far two that caused (different) errors on dmptool-dev are:
- DMP Template from DCC - I just received a "Bad Gateway" message for all file formats
- USGS DMP Guidance template

1 - Details for plans that threw errors (first and last plan in list)
<img width="855" alt="screen shot 2018-02-23 at 12 03 57 pm" src="https://user-images.githubusercontent.com/12703638/36614588-0f279d4c-1892-11e8-80f9-c9a03c880344.png">

2 - No Method error for USGS DMP Template
<img width="812" alt="screen shot 2018-02-23 at 12 02 35 pm" src="https://user-images.githubusercontent.com/12703638/36614579-0a863d02-1892-11e8-97a6-3e93423ab0ed.png">

**Comment by mxsstrong** [comment]
https://dmptool-dev.cdlib.org/plans/1265/download - this is no longer causing an error in dev.

**Comment by stephaniesimms** [comment]
for the USGS template I get the same No Method error for text format only. All other file formats work.

for the DMP Template from

**Comment by briri** [comment]
This should be ok now. I'm not able to replicate the Bad Gateway error. I think it may just be a glitch with the dev data. I've tested several plans based on the DCC template in stage with no issues

**Comment by stephaniesimms** [comment]
yes the USGS is fixed! i won't worry about the other one since it's difficult to distinguish bad data from bugs at this point.

**Comment by briri** [comment]
Bad Gateway usually happens when the server is unable to respond to the request. I think the DCC one may even have been a situation where you tried to access it while the site was being restarted. Did it happen multiple times or just once? We can verify this afternoon once the migration has been run on stage.

**Comment by stephaniesimms** [comment]
i've tested it about 10 times now over a few days and it happens every time. will test again post migration.
