### ISSUE TITLE
IES template bad data 

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#96]
When I opened an IES plan to inspect and download on dmptool-dev I noticed that the bad/weird data migration carried over to plans based on that template. In the screenshot below there should just be one phase, the others are duplicates. I think the solution is to delete the extra phases. 

<img width="865" alt="screen shot 2018-02-23 at 12 17 57 pm" src="https://user-images.githubusercontent.com/12703638/36615166-3296b4e6-1894-11e8-93fc-7ffcf5824d35.png">

**Comment by briri** [comment]
yeah this one was a mess. cleaned up on dmp2-stg and will be ported over correctly during the next migration

**Comment by stephaniesimms** [comment]
okay thanks. i'll take a look at the same plan on dmptool-dev once you port over and make sure there's only one write plan tab. will leave the issue here for now.

**Comment by stephaniesimms** [comment]
data clean-up success! thanks @briri
