### ISSUE TITLE
API token should be created by default for Admins

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#98]
I thought this was working on Roadmap, but it doesn't appear to be on dmptool servers. I can't access the Usage dashboard (screenshot below). We want to issue an API token and allow anyone w/Admin privileges to use it by default.

<img width="1018" alt="screen shot 2018-02-23 at 12 59 27 pm" src="https://user-images.githubusercontent.com/12703638/36616703-92b56f34-1899-11e8-8fa6-f84483b23904.png">

**Comment by briri** [comment]
just need to run the rake task

**Comment by briri** [comment]
fixed rake task (and contributed back to roadmap). Updated dmptool-dev and dmptool-stg and @bhavi added a step to the migration process to run the task after the data migration.

**Comment by stephaniesimms** [comment]
i can see Usage! closing.
